# Generated by Django 6.1 on 2026-09-28 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('starred_by', models.ManyToManyField(blank=True, db_table='main_project_starred_by', related_name='starred_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_project',
                'ordering': ['pk'],
            },
            )],
        ),
    ]
