# Generated by Django 6.1 on 2026-09-28 07:02

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_project_starred_by'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('project', models.CharField(blank=True, max_length=255)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='full-time', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField(default=datetime.date.today)),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_experience',
            },
            )],
        ),
    ]
