# Generated by Django 6.1 on 2026-09-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_update_experience_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
